import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [question, setQuestion] = useState();
  const [answers, setAnswers] = useState();

  const handleQuestion = (e) => {
    setQuestion(e);
  };

  const handleClick = () => {
    setAnswers(null);

    fetch(`http://askto-me.netlify.app/api/openapi?questions=${question}?.`)
      .then((response) => response.json())
      .then((res) => {
        console.log(res);
        setAnswers(res.data.choices[0].text);
      })
      .catch((e) => console.log(e));
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Ask To Me</title>
        <meta name="description" content="Generated by Ask To Me" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a>&quot; Ask To Me &quot;</a>
        </h1>

        <p className={styles.description}>
          Ketik pertanyaan anda di bawah ini{" "}
        </p>
        <p style={{ color: "white" }}>Pertanyaan</p>
        <textarea
          className={styles.card}
          style={{
            backgroundColor: "black",
            maxWidth: "800px",
            minWidth: "630px",
            borderColor: "white",
            textAlign: "center",
            paddingTop: "20px",
          }}
          onChange={(e) => handleQuestion(e.target.value)}
        ></textarea>
        <div
          style={{
            color: "white",
            cursor: "pointer",
            border: "1px solid black",
            padding: "10px 15px",
            borderRadius: "8px",
            backgroundColor: "blue",
          }}
          onClick={handleClick}
        >
          Cari Jawaban
        </div>
        {answers !== null ? (
          <div style={{ textAlign: "center" }}>
            <textarea
              rows={20}
              className={styles.card}
              style={{
                backgroundColor: "black",
                maxWidth: "800px",
                minWidth: "630px",
                border: "1px solid black",
                paddingTop: "0px",
                textAlign: "center",
              }}
            >
              {answers}
            </textarea>
          </div>
        ) : (
          <div class="spinner">
            <div class="rect1"></div>
            <div class="rect2"></div>
            <div class="rect3"></div>
            <div class="rect4"></div>
            <div class="rect5"></div>
          </div>
        )}

        <div className={styles.grid}>
          <a href="https://github.com/ZainiNijar" className={styles.card}>
            <h3>Github &rarr;</h3>
          </a>

          <a href="https://instagram.com/zaini.nijar" className={styles.card}>
            <h3>Instagram &rarr;</h3>
          </a>

          <a href="https://facebook.com/zaininijar" className={styles.card}>
            <h3>Facebook &rarr;</h3>
          </a>

          <a href="https://instagram.com/pasamandev" className={styles.card}>
            <h3>My Community &rarr;</h3>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a>Powered by Zaini Nijar</a>
      </footer>
    </div>
  );
}
